suggestions for docker setup
zeckson/125753-yeticave-1 pull request #1
Opened 2018-09-24 16:37 UTC by caseycs

2018-09-24 20:27 UTC, zeckson requested changes

2018-09-24 20:27 UTC, zeckson commented on docker-compose.yml
> +    - ./nginx/yeticave.local.conf:/etc/nginx/sites-enabled/default
непонятно как это будет монтироваться, если ты выключил `VOLUME` в образе `VOLUME /etc/nginx/sites-enabled`

2018-09-24 20:30 UTC, merged

2018-09-24 20:41 UTC, caseycs commented on docker-compose.yml
> +    - ./nginx/yeticave.local.conf:/etc/nginx/sites-enabled/default
VOLUME декларирует, что указанный путь в контейнере всегда будет в отдельном volume, который останется жить и после удаления контейнера. Т.е. если 100 раз стартовать и удалить контейнер, в котором объявлено 5 volume - останется 500 хвостов. Их можно посмотреть через `docker volume ls`.

Монтирование же локальных путей возможно всегда и в любое место контейнера, и не зависит от того, что объявлено как volume внутри dockerfile.

2018-09-25 04:04 UTC, zeckson commented on docker-compose.yml
> +    - ./nginx/yeticave.local.conf:/etc/nginx/sites-enabled/default
Ага, это всё прояснило! Спасибо!